# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.xwmooc.net
title: xwMOOC
email: kwangchun.lee.7@gmail.com
description: > # "대한민국과 한국어를 이해하는 모든 사람을 위해 천원($1) 정보교육으로 더불어 사는 세상 만들기 프로젝트. 카네기멜론 대학의 쟈넷 윙 교수는 이론적 사고(Theoretical Thinking), 실험적 사고(Experimental Thinking)와 더불어 컴퓨터적 사고(Computational Thinking)가 향후 인간의 사고 체제를 지배하는 중추적인 역할을 할 것을 주장했다. 컴퓨터적 사고와 통계적 사고를 배운 사람과 그렇지 못한 사람과의 차이는 산업경제 체제에서 빈부격차보다 더욱 커다란 디지털 경제의 정보 불평등(Digital Divide)를 야기할 것으로 예측됨에 이를 해소하고, 최소한으로 줄이는데 작게나마 기여하고자 한다."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/xwmooc
  - title: github
    url: https://github.com/xwmooc
